[window]
dimensions = { columns = 120, lines = 34 }
padding = { x = 12, y = 10 }
dynamic_padding = true
decorations = "Buttonless"
decorations_theme_variant = "Light"
dynamic_title = true
opacity = 1
blur = false
option_as_alt = "Both"

[scrolling]
history = 100000
multiplier = 3

[font]
size = 15.0
builtin_box_drawing = true

[font.normal]
family = "IoskeleyMono Nerd Font"
style = "Regular"

[font.bold]
family = "IoskeleyMono Nerd Font"
style = "Bold"

[font.italic]
family = "IoskeleyMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "IoskeleyMono Nerd Font"
style = "Bold Italic"

[cursor]
style = { shape = "Beam", blinking = "On" }
unfocused_hollow = true

[selection]
save_to_clipboard = false

[mouse]
hide_when_typing = true

[env]
TERM = "xterm-256color"

[terminal]
osc52 = "OnlyCopy"

[colors.primary]
background = "#ffffff"
foreground = "#000000"
bright_foreground = "#000000"

[colors.cursor]
text = "#ffffff"
cursor = "#000000"

[colors.vi_mode_cursor]
text = "#ffffff"
cursor = "#0031a9"

[colors.selection]
text = "#000000"
background = "#bdbdbd"

[colors.search.matches]
foreground = "#000000"
background = "#bdbdbd"

[colors.search.focused_match]
foreground = "#000000"
background = "#f2e900"

[colors.normal]
black = "#000000"
red = "#a60000"
green = "#006800"
yellow = "#6f5500"
blue = "#0031a9"
magenta = "#721045"
cyan = "#005e8b"
white = "#bfbfbf"

[colors.bright]
black = "#595959"
red = "#972500"
green = "#315b00"
yellow = "#884900"
blue = "#354fcf"
magenta = "#531ab6"
cyan = "#005f5f"
white = "#ffffff"

[[keyboard.bindings]]
key = "Left"
mods = "Command"
chars = "\u001B[H"

[[keyboard.bindings]]
key = "Right"
mods = "Command"
chars = "\u001B[F"

[[keyboard.bindings]]
key = "Left"
mods = "Option"
chars = "\u001Bb"

[[keyboard.bindings]]
key = "Right"
mods = "Option"
chars = "\u001Bf"

[[keyboard.bindings]]
key = "Back"
mods = "Command"
chars = "\u0015"

[[keyboard.bindings]]
key = "Back"
mods = "Option"
chars = "\u001B\u007F"
