[colors.primary]
background = "#000000"
foreground = "#ffffff"
bright_foreground = "#ffffff"

[colors.cursor]
text = "#000000"
cursor = "#ffffff"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#2fafff"

[colors.selection]
text = "#ffffff"
background = "#5a5a5a"

[colors.search.matches]
foreground = "#ffffff"
background = "#5a5a5a"

[colors.search.focused_match]
foreground = "#000000"
background = "#d0bc00"

[colors.normal]
black = "#000000"
red = "#ff5f59"
green = "#44bc44"
yellow = "#d0bc00"
blue = "#2fafff"
magenta = "#feacd0"
cyan = "#00d3d0"
white = "#989898"

[colors.bright]
black = "#989898"
red = "#ff7f9f"
green = "#00c06f"
yellow = "#fec43f"
blue = "#79a8ff"
magenta = "#b6a0ff"
cyan = "#6ae4b9"
white = "#ffffff"
